### ISSUE TITLE
`OpenInExcel` needs to find the local Excel copy or use the dot net API for Excel

### ISSUE THREAD

**Issue by eirannejad** [gtalarico/pyrevitplus#1]
I'm using the 2014 Office so this script can not find the excel version on my machine.

![2014excel](https://cloud.githubusercontent.com/assets/8197916/18360278/378de05e-75b2-11e6-8fa9-4a987df877eb.png)

**Comment by gtalarico** [comment]
Yes, good catch.
Hasn't been properly tested.
Do you know if it's located in the same location as indicated in the err
msg?
If not, I can find a list of the most common install locations, try them,
and if it fails, prompt user.

- Gui
--
[ Gui Talarico ]
[ gtalarico@gmail.com ]

**Comment by eirannejad** [comment]
It's here:

C:\Program Files (x86)\Microsoft Office\Office14\

**Comment by gtalarico** [comment]
I will take care of it

**Comment by gtalarico** [comment]
Additional paths added on db5d2743443a016f8a92d617110503a1ca3804e5

**Comment by eirannejad** [comment]
Beautiful. I’ll test this tomorrow at the office for our office versions. BTW, this is the report that I get when updating pyrevitplus using the package manager

**Comment by gtalarico** [comment]
Did you mean to attach something?

Gui Talarico
[ mobile ]

**Comment by eirannejad** [comment]
Uhm it is attached. I can see it on mine :/ here it is again

**Comment by gtalarico** [comment]
weird, cant see it! :(

![image](https://cloud.githubusercontent.com/assets/9513968/18414135/400e1cc6-778d-11e6-96ec-bc260f7405af.png)

**Comment by gtalarico** [comment]
but anyhow, should work better now. It's checking 4 different places

**Comment by eirannejad** [comment]
hold on. my bad I was responding via an email and was attaching it there...Got turn of these email notifications :)))) here it is

![pmupdate](https://cloud.githubusercontent.com/assets/8197916/18414146/7202193a-7774-11e6-974c-714417b22172.png)

**Comment by eirannejad** [comment]
Everything seems okay just wanted you to see the report...

**Comment by gtalarico** [comment]
oh yes. I thought you were talking about the excel opener! hehe
--
I saw this early. It only happens on updating, not on fresh install.

it still works, but it's not doing a clear git checkout out; not sure why.
If you click *remove* and then *install* again, and it clears it up.
We can probably fix it by adding some -options to the git command.
I will have to look into it.

- Gui
--
[ Gui Talarico ]
[ gtalarico@gmail.com ]
