### ISSUE TITLE
Error message Open in Excel

### ISSUE THREAD

**Issue by aumaco** [gtalarico/pyrevitplus#13]
I'm getting this message in "Open in Excel" tool.

[Error](http://imgur.com/a/bUhdS)

**Comment by gtalarico** [comment]
Thanks for pointing this out. I have to update it to the latest rpw

**Comment by gtalarico** [comment]
Fixed  on https://github.com/gtalarico/pyrevitplus/commit/4dd961fb9006250d558846d6dd148de5dff140e6
