### ISSUE TITLE
Crop Image tool fails

### ISSUE THREAD

**Issue by benhumphrey** [gtalarico/pyrevitplus#14]
I get this error when running crop image in Revit 2015 on pyRevit 4.5:

Image.pushbutton\script.py", line 108, in 
NameError: global name '__window__' is not defined

**Comment by gtalarico** [comment]
Hi @benhumphrey  - these tools have not been updated to be Compatible with pyRevit 4.5

**Comment by gtalarico** [comment]
Just pushed a commit that comments out those calls.
I don't revit on the computer I am using at the moment.
Please update and let me know if it fixes.

**Comment by benhumphrey** [comment]
Unfortunately, it looks to have made it worse. See attached error log. Previous version loaded with no errors, but bombed out just on crop image. With this version, errors as per the attached, but the tab still loads. Crop Image does not work, but with a new error this time.
[error.log](https://github.com/gtalarico/pyrevitplus/files/1665060/error.log)

**Comment by gtalarico** [comment]
Ah shit. I think I messed something up with my batch find and replace

**Comment by eirannejad** [comment]
Resolved
