### ISSUE TITLE
Errors during the installation process / reloading

### ISSUE THREAD

**Issue by Thomas84** [gtalarico/pyrevitplus#15]
is it critical or should can I ignore the errors?

![image](https://user-images.githubusercontent.com/5624034/35731039-863a2708-0814-11e8-8f2f-b6df3ea9137d.png)

```
INFO: [Reload] Reloading.... 

INFO: [pyrevit.loader.sessioninfo] pyRevit version: 4.4:08a3297 -  with  in Portland, OR 

INFO: [pyrevit.loader.sessioninfo] Host is Autodesk Revit 2018 (build: 20170927_1515(x64) id: 6272) 

INFO: [pyrevit.loader.sessioninfo] Running on: 2.7.7 (IronPython 2.7.7 (2.7.7.0) on .NET 4.0.30319.42000 (64-bit)) 

INFO: [pyrevit.loader.sessioninfo] Home Directory is: C:/ProgramData/pyRevit/pyRevit-v4/pyRevit 

INFO: [pyrevit.loader.sessioninfo] Session uuid is: 99596b9c-080b-11e8-8a0a-79021c459055 

INFO: [pyrevit.loader.sessioninfo] Base assembly is: pyRevit_2018_27e577b999513998_PyRevitBaseClasses 

INFO: [pyrevit.loader.sessioninfo] Config file is: C:/Users/tvogt/AppData/Roaming/pyRevit/pyRevit_config.ini 

INFO: [pyrevit.extensions.extensionmgr] UI Extension successfuly loaded from cache: pyRevitCore 

INFO: [pyrevit.extensions.extensionmgr] Skipping disabled ui extension: pyRevitDevTools 


ERROR: [pyrevit.extensions.genericcomps] Error parsing script file: C:/ProgramData/pyRevit/pyRevit-v4/pyRevit/extensions/PyRevitPlus.extension/pyRevitPlus.tab/Image.panel/Crop Image.pushbutton/script.py | Error parsing script file: C:/ProgramData/pyRevit/pyRevit-v4/pyRevit/extensions/PyRevitPlus.extension/pyRevitPlus.tab/Image.panel/Crop Image.pushbutton/script.py | expected an indented block 

Traceback: 
 File "C:/ProgramData/pyRevit/pyRevit-v4/pyRevit/pyrevitlib/pyrevit/extensions/genericcomps.py", line 341, in _analyse_python_script 
 script_content = ScriptFileParser(self.get_full_script_address()) 



ERROR: [pyrevit.extensions.genericcomps] Error parsing script file: C:/ProgramData/pyRevit/pyRevit-v4/pyRevit/extensions/PyRevitPlus.extension/pyRevitPlus.tab/Smart Align.panel/smartalign.stack3/Distribute.pulldown/Horizontal.pushbutton/script.py | Error parsing script file: C:/ProgramData/pyRevit/pyRevit-v4/pyRevit/extensions/PyRevitPlus.extension/pyRevitPlus.tab/Smart Align.panel/smartalign.stack3/Distribute.pulldown/Horizontal.pushbutton/script.py | expected an indented block 

Traceback: 
 File "C:/ProgramData/pyRevit/pyRevit-v4/pyRevit/pyrevitlib/pyrevit/extensions/genericcomps.py", line 341, in _analyse_python_script 
 script_content = ScriptFileParser(self.get_full_script_address()) 



ERROR: [pyrevit.extensions.genericcomps] Error parsing script file: C:/ProgramData/pyRevit/pyRevit-v4/pyRevit/extensions/PyRevitPlus.extension/pyRevitPlus.tab/Smart Align.panel/smartalign.stack3/Distribute.pulldown/Vertical.pushbutton/script.py | Error parsing script file: C:/ProgramData/pyRevit/pyRevit-v4/pyRevit/extensions/PyRevitPlus.extension/pyRevitPlus.tab/Smart Align.panel/smartalign.stack3/Distribute.pulldown/Vertical.pushbutton/script.py | expected an indented block 

Traceback: 
 File "C:/ProgramData/pyRevit/pyRevit-v4/pyRevit/pyrevitlib/pyrevit/extensions/genericcomps.py", line 341, in _analyse_python_script 
 script_content = ScriptFileParser(self.get_full_script_address()) 



ERROR: [pyrevit.extensions.genericcomps] Error parsing script file: C:/ProgramData/pyRevit/pyRevit-v4/pyRevit/extensions/PyRevitPlus.extension/pyRevitPlus.tab/Smart Align.panel/smartalign.stack3/Horizontal.pulldown/Align Center.pushbutton/script.py | Error parsing script file: C:/ProgramData/pyRevit/pyRevit-v4/pyRevit/extensions/PyRevitPlus.extension/pyRevitPlus.tab/Smart Align.panel/smartalign.stack3/Horizontal.pulldown/Align Center.pushbutton/script.py | expected an indented block 

Traceback: 
 File "C:/ProgramData/pyRevit/pyRevit-v4/pyRevit/pyrevitlib/pyrevit/extensions/genericcomps.py", line 341, in _analyse_python_script 
 script_content = ScriptFileParser(self.get_full_script_address()) 



ERROR: [pyrevit.extensions.genericcomps] Error parsing script file: C:/ProgramData/pyRevit/pyRevit-v4/pyRevit/extensions/PyRevitPlus.extension/pyRevitPlus.tab/Smart Align.panel/smartalign.stack3/Horizontal.pulldown/Align Left.pushbutton/script.py | Error parsing script file: C:/ProgramData/pyRevit/pyRevit-v4/pyRevit/extensions/PyRevitPlus.extension/pyRevitPlus.tab/Smart Align.panel/smartalign.stack3/Horizontal.pulldown/Align Left.pushbutton/script.py | expected an indented block 

Traceback: 
 File "C:/ProgramData/pyRevit/pyRevit-v4/pyRevit/pyrevitlib/pyrevit/extensions/genericcomps.py", line 341, in _analyse_python_script 
 script_content = ScriptFileParser(self.get_full_script_address()) 



ERROR: [pyrevit.extensions.genericcomps] Error parsing script file: C:/ProgramData/pyRevit/pyRevit-v4/pyRevit/extensions/PyRevitPlus.extension/pyRevitPlus.tab/Smart Align.panel/smartalign.stack3/Horizontal.pulldown/Align Right.pushbutton/script.py | Error parsing script file: C:/ProgramData/pyRevit/pyRevit-v4/pyRevit/extensions/PyRevitPlus.extension/pyRevitPlus.tab/Smart Align.panel/smartalign.stack3/Horizontal.pulldown/Align Right.pushbutton/script.py | expected an indented block 

Traceback: 
 File "C:/ProgramData/pyRevit/pyRevit-v4/pyRevit/pyrevitlib/pyrevit/extensions/genericcomps.py", line 341, in _analyse_python_script 
 script_content = ScriptFileParser(self.get_full_script_address()) 



ERROR: [pyrevit.extensions.genericcomps] Error parsing script file: C:/ProgramData/pyRevit/pyRevit-v4/pyRevit/extensions/PyRevitPlus.extension/pyRevitPlus.tab/Smart Align.panel/smartalign.stack3/Vertical.pulldown/Align Bottom.pushbutton/script.py | Error parsing script file: C:/ProgramData/pyRevit/pyRevit-v4/pyRevit/extensions/PyRevitPlus.extension/pyRevitPlus.tab/Smart Align.panel/smartalign.stack3/Vertical.pulldown/Align Bottom.pushbutton/script.py | expected an indented block 

Traceback: 
 File "C:/ProgramData/pyRevit/pyRevit-v4/pyRevit/pyrevitlib/pyrevit/extensions/genericcomps.py", line 341, in _analyse_python_script 
 script_content = ScriptFileParser(self.get_full_script_address()) 



ERROR: [pyrevit.extensions.genericcomps] Error parsing script file: C:/ProgramData/pyRevit/pyRevit-v4/pyRevit/extensions/PyRevitPlus.extension/pyRevitPlus.tab/Smart Align.panel/smartalign.stack3/Vertical.pulldown/Align Center.pushbutton/script.py | Error parsing script file: C:/ProgramData/pyRevit/pyRevit-v4/pyRevit/extensions/PyRevitPlus.extension/pyRevitPlus.tab/Smart Align.panel/smartalign.stack3/Vertical.pulldown/Align Center.pushbutton/script.py | expected an indented block 

Traceback: 
 File "C:/ProgramData/pyRevit/pyRevit-v4/pyRevit/pyrevitlib/pyrevit/extensions/genericcomps.py", line 341, in _analyse_python_script 
 script_content = ScriptFileParser(self.get_full_script_address()) 



ERROR: [pyrevit.extensions.genericcomps] Error parsing script file: C:/ProgramData/pyRevit/pyRevit-v4/pyRevit/extensions/PyRevitPlus.extension/pyRevitPlus.tab/Smart Align.panel/smartalign.stack3/Vertical.pulldown/Align Top.pushbutton/script.py | Error parsing script file: C:/ProgramData/pyRevit/pyRevit-v4/pyRevit/extensions/PyRevitPlus.extension/pyRevitPlus.tab/Smart Align.panel/smartalign.stack3/Vertical.pulldown/Align Top.pushbutton/script.py | expected an indented block 

Traceback: 
 File "C:/ProgramData/pyRevit/pyRevit-v4/pyRevit/pyrevitlib/pyrevit/extensions/genericcomps.py", line 341, in _analyse_python_script 
 script_content = ScriptFileParser(self.get_full_script_address()) 


INFO: [pyrevit.extensions.extensionmgr] UI Extension successfuly parsed: PyRevitPlus 

INFO: [pyrevit.extensions.extensionmgr] Updating cache for ui_extension: PyRevitPlus 

INFO: [pyrevit.extensions.extensionmgr] UI Extension successfuly loaded from cache: pyRevitTools 

INFO: [pyrevit.extensions.extensionmgr] Skipping disabled ui extension: pyRevitTutor 

INFO: [pyrevit.loader.sessionmgr] Extension assembly created: pyRevitCore 

INFO: [pyrevit.loader.sessionmgr] UI created for extension: pyRevitCore 

INFO: [pyrevit.loader.sessionmgr] Extension assembly created: PyRevitPlus 

INFO: [pyrevit.loader.sessionmgr] UI created for extension: PyRevitPlus 

INFO: [pyrevit.loader.sessionmgr] Extension assembly created: pyRevitTools 

INFO: [pyrevit.loader.sessionmgr] UI created for extension: pyRevitTools 

INFO: [pyrevit.loader.sessionmgr] Load time: 4.2315 seconds  
```

**Comment by gtalarico** [comment]
I made a very unsuccessful batch and replace mentioned below and broke everything. I will fix it as soon as I have chance 
https://github.com/gtalarico/pyrevitplus/issues/14

**Comment by gtalarico** [comment]
Please disable the extension for now and will post back when it's fixed

**Comment by Thomas84** [comment]
it is maybe my fail, because I have used the update button...

**Comment by adamrees89** [comment]
Has the tool been removed from the pyRevit extensions dialogue?

![image](https://user-images.githubusercontent.com/5112449/37276432-91d2d032-25d9-11e8-865b-f4e28629ad65.png)

**Comment by gtalarico** [comment]
Sorry for the late reply guys!
If it was, it's probably because in my last attempt to update the scripts I did a bad batch find and replace and broke all scripts at once, so I am guessing @eirannejad removed it : )

**Comment by eirannejad** [comment]
Yeah removed all extensions from list at pyRevit 4.5 upgrade. Other extensions upgraded and tested with 4.5 so the were added back. Sorry for the missing pyRevitPlus :/

**Comment by Robbo1234** [comment]
Hi Ehsan,

Is it still possible for me to load the pyRevitPlus extension?

Rob

**Comment by eirannejad** [comment]
Yes it is. As a quick solution, download the ZIP archive of the master branch
https://github.com/gtalarico/pyrevitplus/archive/master.zip

Unzip too a directory of your choice.
Rename `pyrevitplus-master` to `pyRevitPlus.extension` and place it in `%appdata%\pyRevit\Extensions`
So when done you should have this directory structure:
`%appdata%\pyRevit\Extensions\pyRevitPlus.extension\pyRevitPlus.tab`

Then reload pyRevit and it should load the pyRevitPlus extension. pyRevitPlus hasn't been tested with the new pyRevit changes so tools might not all work.

I'll add it back again in 4.6.9 which is being published this weekend.

**Comment by Robbo1234** [comment]
Thanks Ehsan

**Comment by gtalarico** [comment]
I should warn you: these tools stopped working because of breaking changes in pyrevit so they might not work on latest pyrevit. 

I have been meaning to o through the code base and update it but I haven't gotten around to it

**Comment by eirannejad** [comment]
@Robbo1234 Ya let me know if there is a tool that you absolutely need and I can take a look and update the code as well and send @gtalarico a pull request.

**Comment by Robbo1234** [comment]
Happy new year Eshan

I just installed PyRevit 4.6.9

For some reason PyRevitPlus extension installed in Revit 2016 but when I tried enabling PyRevitPlus in Revit 2017.2 is didn't install.

Refer to screen shot below

![image](https://user-images.githubusercontent.com/8776947/50590786-3dfd6780-0e84-11e9-8773-1d1f2a331352.png)



﻿______

INFO: [Reload] Reloading.... 

INFO: [pyrevit.loader.sessioninfo] pyRevit version: 4.6.8 - </> with  in ['pdx', 'hio', 'rno'] 

INFO: [pyrevit.loader.sessioninfo] pyRevit Rocket Mode enabled.  

INFO: [pyrevit.loader.sessioninfo] Host is Autodesk Revit 2017 (build: 20171027_0315(x64) id: 13696) 

INFO: [pyrevit.loader.sessioninfo] Running on: 2.7.7 (IronPython 2.7.7 (2.7.7.0) on .NET 4.0.30319.42000 (64-bit)) 

INFO: [pyrevit.loader.sessioninfo] User is: robcross 

INFO: [pyrevit.loader.sessioninfo] Home Directory is: C:\Program Files\pyRevit-Master 

INFO: [pyrevit.loader.sessioninfo] Session uuid is: fb016b16-b23c-4200-842a-5c7d8525a03e 

INFO: [pyrevit.loader.sessioninfo] Base assembly is: pyRevit_2017_e3a4bf62ce2642d1_PyRevitBaseClasses 

INFO: [pyrevit.loader.sessioninfo] Config file is (User): C:\Users\rob.cross\AppData\Roaming\pyRevit\pyRevit_config.ini 

INFO: [pyrevit.extensions.extensionmgr] UI Extension successfuly loaded from cache: pyRevitCore 


ERROR: [pyrevit.extensions.genericcomps] Error while parsing file: 
C:/Program Files/pyRevit-Master/extensions/pyrevitplus.extension/pyRevitPlus.tab/Image.panel/Crop Image.pushbutton/script.py 
Error type: IndentationError 
Error Message: expected an indented block 
Line/Column: 109/1 
Line Text: 



ERROR: [pyrevit.extensions.genericcomps] Error while parsing file: 
C:/Program Files/pyRevit-Master/extensions/pyrevitplus.extension/pyRevitPlus.tab/Smart Align.panel/smartalign.stack3/Distribute.pulldown/Horizontal.pushbutton/script.py 
Error type: IndentationError 
Error Message: expected an indented block 
Line/Column: 26/1 
Line Text: 



ERROR: [pyrevit.extensions.genericcomps] Error while parsing file: 
C:/Program Files/pyRevit-Master/extensions/pyrevitplus.extension/pyRevitPlus.tab/Smart Align.panel/smartalign.stack3/Distribute.pulldown/Vertical.pushbutton/script.py 
Error type: IndentationError 
Error Message: expected an indented block 
Line/Column: 27/22 
Line Text: # ALIGN = Align.HDIST 



ERROR: [pyrevit.extensions.genericcomps] Error while parsing file: 
C:/Program Files/pyRevit-Master/extensions/pyrevitplus.extension/pyRevitPlus.tab/Smart Align.panel/smartalign.stack3/Horizontal.pulldown/Align Center.pushbutton/script.py 
Error type: IndentationError 
Error Message: expected an indented block 
Line/Column: 26/1 
Line Text: 



ERROR: [pyrevit.extensions.genericcomps] Error while parsing file: 
C:/Program Files/pyRevit-Master/extensions/pyrevitplus.extension/pyRevitPlus.tab/Smart Align.panel/smartalign.stack3/Horizontal.pulldown/Align Left.pushbutton/script.py 
Error type: IndentationError 
Error Message: expected an indented block 
Line/Column: 27/24 
Line Text: # ALIGN = Align.HCENTER 



ERROR: [pyrevit.extensions.genericcomps] Error while parsing file: 
C:/Program Files/pyRevit-Master/extensions/pyrevitplus.extension/pyRevitPlus.tab/Smart Align.panel/smartalign.stack3/Horizontal.pulldown/Align Right.pushbutton/script.py 
Error type: IndentationError 
Error Message: expected an indented block 
Line/Column: 28/22 
Line Text: # ALIGN = Align.HLEFT 



ERROR: [pyrevit.extensions.genericcomps] Error while parsing file: 
C:/Program Files/pyRevit-Master/extensions/pyrevitplus.extension/pyRevitPlus.tab/Smart Align.panel/smartalign.stack3/Vertical.pulldown/Align Bottom.pushbutton/script.py 
Error type: IndentationError 
Error Message: expected an indented block 
Line/Column: 31/21 
Line Text: # ALIGN = Align.VTOP 



ERROR: [pyrevit.extensions.genericcomps] Error while parsing file: 
C:/Program Files/pyRevit-Master/extensions/pyrevitplus.extension/pyRevitPlus.tab/Smart Align.panel/smartalign.stack3/Vertical.pulldown/Align Center.pushbutton/script.py 
Error type: IndentationError 
Error Message: expected an indented block 
Line/Column: 29/23 
Line Text: # ALIGN = Align.HRIGHT 



ERROR: [pyrevit.extensions.genericcomps] Error while parsing file: 
C:/Program Files/pyRevit-Master/extensions/pyrevitplus.extension/pyRevitPlus.tab/Smart Align.panel/smartalign.stack3/Vertical.pulldown/Align Top.pushbutton/script.py 
Error type: IndentationError 
Error Message: expected an indented block 
Line/Column: 30/24 
Line Text: # ALIGN = Align.VCENTER 


INFO: [pyrevit.extensions.extensionmgr] UI Extension successfuly parsed: pyrevitplus 

INFO: [pyrevit.extensions.extensionmgr] Updating cache for ui_extension: pyrevitplus 

INFO: [pyrevit.extensions.extensionmgr] UI Extension successfuly loaded from cache: pyRevitTags 

INFO: [pyrevit.extensions.extensionmgr] UI Extension successfuly loaded from cache: pyRevitTools 

INFO: [pyrevit.extensions.extensionmgr] Skipping disabled ui extension: pyRevitTutor 


ERROR: [pyrevit.extensions.genericcomps] Error while parsing file: 
C:/Users/rob.cross/AppData/Roaming/pyRevit/Extensions/pyrevitplus.extension/pyRevitPlus.tab/Image.panel/Crop Image.pushbutton/script.py 
Error type: IndentationError 
Error Message: expected an indented block 
Line/Column: 109/1 
Line Text: 



ERROR: [pyrevit.extensions.genericcomps] Error while parsing file: 
C:/Users/rob.cross/AppData/Roaming/pyRevit/Extensions/pyrevitplus.extension/pyRevitPlus.tab/Smart Align.panel/smartalign.stack3/Distribute.pulldown/Horizontal.pushbutton/script.py 
Error type: IndentationError 
Error Message: expected an indented block 
Line/Column: 26/1 
Line Text: 



ERROR: [pyrevit.extensions.genericcomps] Error while parsing file: 
C:/Users/rob.cross/AppData/Roaming/pyRevit/Extensions/pyrevitplus.extension/pyRevitPlus.tab/Smart Align.panel/smartalign.stack3/Distribute.pulldown/Vertical.pushbutton/script.py 
Error type: IndentationError 
Error Message: expected an indented block 
Line/Column: 27/22 
Line Text: # ALIGN = Align.HDIST 



ERROR: [pyrevit.extensions.genericcomps] Error while parsing file: 
C:/Users/rob.cross/AppData/Roaming/pyRevit/Extensions/pyrevitplus.extension/pyRevitPlus.tab/Smart Align.panel/smartalign.stack3/Horizontal.pulldown/Align Center.pushbutton/script.py 
Error type: IndentationError 
Error Message: expected an indented block 
Line/Column: 26/1 
Line Text: 



ERROR: [pyrevit.extensions.genericcomps] Error while parsing file: 
C:/Users/rob.cross/AppData/Roaming/pyRevit/Extensions/pyrevitplus.extension/pyRevitPlus.tab/Smart Align.panel/smartalign.stack3/Horizontal.pulldown/Align Left.pushbutton/script.py 
Error type: IndentationError 
Error Message: expected an indented block 
Line/Column: 27/24 
Line Text: # ALIGN = Align.HCENTER 



ERROR: [pyrevit.extensions.genericcomps] Error while parsing file: 
C:/Users/rob.cross/AppData/Roaming/pyRevit/Extensions/pyrevitplus.extension/pyRevitPlus.tab/Smart Align.panel/smartalign.stack3/Horizontal.pulldown/Align Right.pushbutton/script.py 
Error type: IndentationError 
Error Message: expected an indented block 
Line/Column: 28/22 
Line Text: # ALIGN = Align.HLEFT 



ERROR: [pyrevit.extensions.genericcomps] Error while parsing file: 
C:/Users/rob.cross/AppData/Roaming/pyRevit/Extensions/pyrevitplus.extension/pyRevitPlus.tab/Smart Align.panel/smartalign.stack3/Vertical.pulldown/Align Bottom.pushbutton/script.py 
Error type: IndentationError 
Error Message: expected an indented block 
Line/Column: 31/21 
Line Text: # ALIGN = Align.VTOP 



ERROR: [pyrevit.extensions.genericcomps] Error while parsing file: 
C:/Users/rob.cross/AppData/Roaming/pyRevit/Extensions/pyrevitplus.extension/pyRevitPlus.tab/Smart Align.panel/smartalign.stack3/Vertical.pulldown/Align Center.pushbutton/script.py 
Error type: IndentationError 
Error Message: expected an indented block 
Line/Column: 29/23 
Line Text: # ALIGN = Align.HRIGHT 



ERROR: [pyrevit.extensions.genericcomps] Error while parsing file: 
C:/Users/rob.cross/AppData/Roaming/pyRevit/Extensions/pyrevitplus.extension/pyRevitPlus.tab/Smart Align.panel/smartalign.stack3/Vertical.pulldown/Align Top.pushbutton/script.py 
Error type: IndentationError 
Error Message: expected an indented block 
Line/Column: 30/24 
Line Text: # ALIGN = Align.VCENTER 


INFO: [pyrevit.extensions.extensionmgr] UI Extension successfuly parsed: pyrevitplus 

INFO: [pyrevit.extensions.extensionmgr] Updating cache for ui_extension: pyrevitplus 

INFO: [pyrevit.loader.sessionmgr] Extension assembly created: pyRevitCore 

INFO: [pyrevit.loader.sessionmgr] Extension assembly created: pyrevitplus 

INFO: [pyrevit.loader.sessionmgr] Extension assembly created: pyRevitTags 

INFO: [pyrevit.loader.sessionmgr] Extension assembly created: pyRevitTools 

INFO: [pyrevit.loader.sessionmgr] Extension assembly created: pyrevitplus 

INFO: [pyrevit.loader.sessionmgr] UI created for extension: pyRevitCore 


ERROR: [pyrevit.loader.uimaker] UI error: Can not create tab: Too many tabs have been created by the API. Instead, you may add your Ribbon Panels to the Add-Ins tab.

INFO: [pyrevit.loader.sessionmgr] UI created for extension: pyrevitplus 

INFO: [pyrevit.loader.sessionmgr] UI created for extension: pyRevitTags 

INFO: [pyrevit.loader.sessionmgr] UI created for extension: pyRevitTools 


ERROR: [pyrevit.loader.uimaker] UI error: Can not create tab: Too many tabs have been created by the API. Instead, you may add your Ribbon Panels to the Add-Ins tab.

INFO: [pyrevit.loader.sessionmgr] UI created for extension: pyrevitplus 

INFO: [pyrevit.loader.sessionmgr] Load time: 2.80999755859 seconds

**Comment by Robbo1234** [comment]
FYI
I got PyRevitPlus to load in Revit 2017.2

I had to remove some Revit addins because PyRevit stated that I had too many tabs open in Revit.

Can this be fixed?

**Comment by amadeumagalhaes** [comment]
Hi,

tried to remove some addins and didn't work (do I have to remove all of them ?)...
Do you have other fix for this ?

Thank you !

**Comment by eirannejad** [comment]
Resolved
