### ISSUE TITLE
PyRevitPlus compatiblility with PyRevit 4.5

### ISSUE THREAD

**Issue by Francouize** [gtalarico/pyrevitplus#16]
Hello,

Is PyRevitPlus compatible with PyRevit 4.5 ?
There is a change that seems to go in this direction but I can't find PyRevitPlus in PyRevit Package Manager.

Thanks for your answer ;)

**Comment by gtalarico** [comment]
Hi - unfortunately I have not had time to properly upgrade this library.
I can update you here when I get it updated.

**Comment by Francouize** [comment]
Ok Thanks, your tools are very usefull !

**Comment by eirannejad** [comment]
pyRevitPlus has been added back
