### ISSUE TITLE
Bar chart: Allow for cells with Units

### ISSUE THREAD

**Issue by eirannejad** [gtalarico/pyrevitplus#2]
Is this possible for this to work with non-numerical values e.g. Area, Length, ...

**Comment by gtalarico** [comment]
It works with quantities, lenghts, areas, etc. any numberical values.
But for now you would have to remove *units* from that column so there are only numbers in the cells
![image](https://cloud.githubusercontent.com/assets/9513968/18413926/1317532e-7786-11e6-9cfb-fabe9074be5f.png)

**Comment by eirannejad** [comment]
Got it cool!
