### ISSUE TITLE
Challenge: Can you write a tool that collapses/expands the Project Browser hierarchy? 

### ISSUE THREAD

**Issue by eirannejad** [gtalarico/pyrevitplus#5]

**Comment by gtalarico** [comment]
Haha. Sounds like a nice tool Expand all, collapse all.
looks like it's not exposed by the API:
http://forums.autodesk.com/t5/revit-api-forum/how-to-read-browser-organization-info-from-the-revit-api-2013/td-p/4961214

**Comment by eirannejad** [comment]
I was thinking maybe you know how to grab the standard Windows tree control from the view and collapse and expand the items...Not sure if it is possible though

**Comment by gtalarico** [comment]
I was able to work something pretty roughly, not very elegantly : )
It just SendKeys (Left, Up, Left, Up), but it doesnt't collapse all, only
the root nodes...
