### ISSUE TITLE
Feature Update Request

### ISSUE THREAD

**Issue by thazell** [gtalarico/pyrevitplus#6]
Not sure this is the right place to make a feature request, but can the horizontal align only align the text in a text note with a leader, instead of the entire object (including the leader)?

**Comment by gtalarico** [comment]
Interesting. Haven't tested it yet. 
Currently using bounding box. I will check it out

**Comment by thazell** [comment]
Thanks Gui!

**Comment by gtalarico** [comment]
I think I can fix this by checking for text-bases location (`coord`) before going for the catch all bounding box

**Comment by thazell** [comment]
Awesome!  Does this handle maintaining leader position when moving text/tags?
