### ISSUE TITLE
Issue with installing Revit 2017

### ISSUE THREAD

**Issue by mdengusiak** [gtalarico/pyrevitplus#7]
I am trying to run PyRevit Package Manager and got this window and nothing is happening.
Not sure how to install PyRevit+

![image](https://cloud.githubusercontent.com/assets/14005893/20708425/21183a86-b630-11e6-8be1-54f4716180b5.png)

**Comment by eirannejad** [comment]
@mdengusiak I'll test this out and will update you. Thanks for letting us know

**Comment by gtalarico** [comment]
pyRevit issue
